akapp/urls.py
from django.urls import path
from . import views

app_name = 'akapp'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('anken/list/', views.AnkenListView.as_view(), name='anken_list'),
    path('anken/detail/<int:pk>/', views.AnkenDetailView.as_view(), name='anken_detail'),

    path('anken/create/', views.AnkenCreateView.as_view(), name='anken_create'),
    path('anken/create/complete/', views.AnkenCreateCompleteView.as_view(), name='anken_create_complete'),
    path('anken/update/<int:pk>/', views.AnkenUpdateView.as_view(), name='anken_update'),
    path('anken/delete/<int:pk>/', views.AnkenDeleteView.as_view(), name='anken_delete'),

    path('shuho/create/', views.ShuhoCreateView.as_view(), name='shuho_create'),
    path('shuho/create/complete/', views.ShuhoCreateCompleteView.as_view(), name='shuho_create_complete'),
    path('shuho/update/<int:pk>/', views.ShuhoUpdateView.as_view(), name='shuho_update'),
    path('shuho/delete/<int:pk>/', views.ShuhoDeleteView.as_view(), name='shuho_delete'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akapp.urls')),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


akapp/models.py
from django.db import models
from django.utils import timezone


class Anken(models.Model):
    TANTOUSHA_CHOICES = (
                        ("0", "Aさん"),
                        ("1", "Bさん"),
                        ("2", "Cさん"),
                        )

    KOUMOKU_CHOICES = (
                        ("0", "案件"),
                        ("1", "案件_別途報告"),
                        ("2", "創意工夫展開"),
                        ("3", "自己研鑽"),
                        ("4", "お知らせ"),
                        ("5", "その他"),
                        )

    JOUTAI_CHOICES = (
                        ("0", "対応中"),
                        ("1", "完了"),
                        ("2", "一時休止"),
                        ("3", "未着手"),
                        ("4", "指定しない"),
                        )

    pub_date = models.DateTimeField(verbose_name='日付',default=timezone.now)
    ankenmei = models.CharField(verbose_name='案件名',max_length=200)
    iraibusho = models.CharField(verbose_name='依頼部署',max_length=200)
    iraisha = models.CharField(verbose_name='依頼者',max_length=200)
    nouki = models.DateTimeField(verbose_name='納期')
    mitumorikousu = models.IntegerField(verbose_name='見積工数(H)',default=0)
    naiyou = models.TextField(verbose_name='内容',max_length=1000)
    genjouchi = models.CharField(verbose_name='現状値',max_length=200)
    kitaikouka = models.CharField(verbose_name='期待効果',max_length=200)
    tantousha = models.CharField(verbose_name='担当者',choices=TANTOUSHA_CHOICES,max_length=200)
    koumoku = models.CharField(verbose_name='項目',choices=KOUMOKU_CHOICES,max_length=200)
    joutai = models.CharField(verbose_name='状態',choices=JOUTAI_CHOICES,max_length=200)
    jissekikousu = models.IntegerField(verbose_name='実績工数(H)',default=0)
    updated_at = models.DateTimeField(verbose_name='更新日時',blank=True, null=True)

    def __str__(self):
        return self.ankenmei


class Shuho(models.Model):
    CATEGORI_CHOICES = (
                            ("0", "環境構築"),
                            ("1", "前処理"),
                            ("2", "分析手法"),
                            ("3", "エッジ・設備"),
                            ("4", "その他"),
                        )

    anken = models.ForeignKey(Anken, verbose_name='案件',on_delete=models.CASCADE)
    pub_date = models.DateTimeField(verbose_name='日付',default=timezone.now)
    naiyou = models.TextField(verbose_name='内容',max_length=1000)
    categori = models.CharField(verbose_name='カテゴリ',choices=CATEGORI_CHOICES,max_length=200)
    updated_at = models.DateTimeField(verbose_name='更新日時',blank=True, null=True)

    def __str__(self):
        return self.anken

akapp/forms.py
from django import forms
from .models import Anken, Shuho
import bootstrap_datepicker_plus as datetimepicker
from django_summernote.widgets import SummernoteWidget



class AnkenForm(forms.ModelForm):
    class Meta:
        model = Anken
        fields = ('pub_date',
                'ankenmei',
                'iraibusho',
                'iraisha',
                'nouki',
                'mitumorikousu',
                'naiyou',
                'genjouchi', 
                'kitaikouka', 
                'tantousha',  
                'koumoku', 
                'joutai', 
                'jissekikousu',
                'updated_at',
                )
        widgets = {
            'nouki': datetimepicker.DateTimePickerInput(
                format='%Y-%m-%d %H:%M:%S',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                }
            ),
            'naiyou': SummernoteWidget(),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pub_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['updated_at'].widget.attrs['readonly'] = 'readonly'
        
                    
class ShuhoForm(forms.ModelForm):
    class Meta:
        model = Shuho
        fields = ('anken',
                'pub_date',
                'naiyou',
                'categori',
                'updated_at',
                )
        widgets = {
            'naiyou': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pub_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['updated_at'].widget.attrs['readonly'] = 'readonly'
        
        

        
        
        
        
    
    

akapp/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import AnkenForm, ShuhoForm
from django.urls import reverse_lazy,reverse
from .models import Anken, Shuho
from django.utils import timezone
from django.shortcuts import render, get_object_or_404


class IndexView(TemplateView):
    template_name = 'akapp/index.html'


class AnkenListView(ListView):
    template_name = 'akapp/anken_list.html'
    model = Anken


class AnkenDetailView(DetailView):
    template_name = 'akapp/anken_detail.html'
    model = Anken


class AnkenCreateView(CreateView):
    template_name = 'akapp/anken_create.html'
    form_class = AnkenForm
    #success_url = reverse_lazy('akapp:anken_create_complete')
    success_url = reverse_lazy('akapp:anken_list')
    

class AnkenCreateCompleteView(TemplateView):
    template_name = 'akapp/anken_create_complete.html'


class AnkenUpdateView(UpdateView):
    template_name = 'akapp/anken_update.html'
    form_class = AnkenForm
    model = Anken
    #success_url = reverse_lazy('akapp:anken_list')

    def get_success_url(self):
        return reverse('akapp:anken_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        anken = form.save(commit=False)
        anken.updated_at = timezone.now()
        anken.save()
        return super().form_valid(form)


class AnkenDeleteView(DeleteView):
    template_name = 'akapp/anken_delete.html'
    model = Anken
    success_url = reverse_lazy('akapp:anken_list')


class ShuhoCreateView(CreateView):
    template_name = 'akapp/shuho_create.html'
    form_class = ShuhoForm
    #success_url = reverse_lazy('akapp:shuho_create_complete')
    
    def get_success_url(self):
        print(self.object.anken.pk)
        return reverse('akapp:anken_detail', kwargs={'pk': self.object.anken.pk})

            
class ShuhoCreateCompleteView(TemplateView):
    template_name = 'akapp/shuho_create_complete.html'


class ShuhoUpdateView(UpdateView):
    template_name = 'akapp/shuho_update.html'
    form_class = ShuhoForm
    model = Shuho
    #success_url = reverse_lazy('akapp:anken_list')
    
    def get_success_url(self):
        print(self.object.anken.pk)
        return reverse('akapp:anken_detail', kwargs={'pk': self.object.anken.pk})

    def form_valid(self, form):
        shuho = form.save(commit=False)
        shuho.updated_at = timezone.now()
        shuho.save()
        return super().form_valid(form)


class ShuhoDeleteView(DeleteView):
    template_name = 'akapp/shuho_delete.html'
    model = Shuho
    #success_url = reverse_lazy('akapp:anken_list')

    def get_success_url(self):
        print(self.object.anken.pk)
        return reverse('akapp:anken_detail', kwargs={'pk': self.object.anken.pk})



akapp/templates/akapp/anken_create.html
{% extends 'akapp/base.html' %}

{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="container">
    <span class="text-secondary">案件新規作成</span><br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="submit" class="btn btn-primary btn-sm" value="保存">
        <input type="reset" class="btn btn-outline-primary btn-sm" value="キャンセル">
        <a href="{% url 'akapp:index' %}">戻る</a>
    </form>
</div>
{% endblock %}



akapp/templates/akapp/anken_create_complete.html
{% extends 'akapp/base.html' %}

{% block content %}
<p>投稿が完了しました！</p>
<a href="{% url 'akapp:index' %}">トップへ戻る</a>
{% endblock %}

akapp/templates/akapp/anken_delete.html
{% extends 'akapp/base.html' %}

{% block content %}
<h3>案件削除</h3>
<form method="post">
    {% csrf_token %}
    <p>{{ anken.pub_date }} {{ anken.ankenmei }} を削除します</p>
    <input type="submit" class="btn btn-danger btn-sm" value="削除">
    <a class="btn btn-outline-primary btn-sm" href="#" onclick="history.back(); return false;">キャンセル</a>
</form>
{% endblock %}

akapp/templates/akapp/anken_detail.html
{% extends 'akapp/base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="div1" style="height:1000px; width:45%; overflow-y:scroll;">
    <div class="p-3 mb-2 bg-light text-dark">
        <table class="table caption-top" >
            <caption class="caption-top">案件詳細</caption>
            <tbody>
                <tr>
                    <th scope="row">日付</th>
                    <td>{{ anken.pub_date }}</td>
                </tr>
                <tr>
                    <th scope="row">案件名</th>
                    <td>{{ anken.ankenmei }}</td>
                </tr>
                <tr>
                    <th scope="row">依頼部署</th>
                    <td>{{ anken.iraibusho }}</td>
                </tr>
                <tr>
                    <th scope="row">依頼者</th>
                    <td>{{ anken.iraisha }}</td>
                </tr>
                <tr>
                    <th scope="row">納期</th>
                    <td>{{ anken.nouki }}</td>
                </tr>
                <tr>
                    <th scope="row">見積工数(H)</th>
                    <td>{{ anken.mitumorikousu }}</td>
                </tr>
                <tr>
                    <th scope="row">内容</th>
                    <td>{{ anken.naiyou | safe }}</td>
                </tr>
                <tr>
                    <th scope="row">現状値</th>
                    <td>{{ anken.genjouchi }}</td>
                </tr>
                <tr>
                    <th scope="row">期待効果</th>
                    <td>{{ anken.kitaikouka }}</td>
                </tr>
                <tr>
                    <th scope="row">担当者</th>
                    <td>{{ anken.get_tantousha_display }}</td>
                </tr>
                <tr>
                    <th scope="row">項目</th>
                    <td>{{ anken.get_koumoku_display }}</td>
                </tr>
                <tr>
                    <th scope="row">状態</th>
                    <td>{{ anken.get_joutai_display }}</td>
                </tr>
                <tr>
                    <th scope="row">実績工数(H)</th>
                    <td>{{ anken.jissekikousu }}</td>
                </tr>
                <tr>
                    <th scope="row">更新日時</th>
                    <td>{{ anken.updated_at }}</td>
                </tr>
            </tbody>
        </table>
        
        <a class="btn btn-secondary btn-sm" href="{% url 'akapp:anken_update' anken.pk %}">編集</a>
        <a class="btn btn-danger btn-sm" href="{% url 'akapp:anken_delete' anken.pk %}">削除</a>
        <a class="btn btn-primary btn-sm" href="{% url 'akapp:shuho_create' %}">週報新規作成</a>
        <a href="{% url 'akapp:anken_list' %}">戻る</a>
    </div>
</div>

<div class="div2" style="height:1000px; width:45%; overflow-y:scroll;">
    {% for shuho in anken.shuho_set.all %}
        <div class="p-3 mb-2 bg-light text-dark">
            <table class="table caption-top">
                <caption class="caption-top">週報一覧</caption>
                    <tbody>
                    <tr>
                        <th scope="row">日付</th>
                        <td>{{ shuho.pub_date }}</td>
                    </tr>
                    <tr>
                        <th scope="row">内容</th>
                        <td>{{ shuho.naiyou | safe }}</td>
                    </tr>
                    <tr>
                        <th scope="row">カテゴリ</th>
                        <td>{{ shuho.get_categori_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">更新日時</th>
                        <td>{{ shuho.updated_at }}</td>
                    </tr>
                    </tbody>
            </table>
            <a class="btn btn-secondary btn-sm" href="{% url 'akapp:shuho_update' shuho.pk %}">編集</a>
            <a class="btn btn-danger btn-sm" href="{% url 'akapp:shuho_delete' shuho.pk %}">削除</a>
        </div>
    {% endfor %}
</div>
{% endblock %}


akapp/templates/akapp/anken_list.html
{% extends 'akapp/base.html' %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <caption class="caption-top">案件一覧</caption>
        <thead>
            <tr>
            <th scope="col">日付</th>
            <th scope="col">更新日時</th>
            <th scope="col">案件名</th>
            <th scope="col">担当者</th>
            <th scope="col">状態</th>
            <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for anken in anken_list %}
            <tr>
            <td>{{ anken.pub_date }}</td>
            <td>{{ anken.updated_at }}</td>
            <td>{{ anken.ankenmei }}</td>
            <td>{{ anken.get_tantousha_display }}</td>
            <td>{{ anken.get_joutai_display }}</td>
            <td><a class="btn btn-secondary btn-sm" href="{% url 'akapp:anken_detail' anken.pk %}">詳細</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary btn-sm" href="{% url 'akapp:anken_create' %}">案件新規作成</a>
    <a href="{% url 'akapp:index' %}">戻る</a>
</div>
{% endblock %}

akapp/templates/akapp/anken_update.html
{% extends 'akapp/base.html' %}

{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="container">
    <span class="text-secondary">案件編集</span><br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="submit" class="btn btn-primary btn-sm" value="保存">
        <input type="reset" class="btn btn-outline-primary btn-sm" value="キャンセル">
        <a href="{% url 'akapp:anken_detail' anken.pk %}">戻る</a>
    </form>
</div>
{% endblock %}

akapp/templates/akapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    
    <!--bootstrap-->
    <link rel="stylesheet" type="text/css" href="{% static 'akapp/css/bootstrap.min.css' %}">
    <script src="{% static 'akapp/js/bootstrap.bundle.min.js' %}"></script>

    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'akapp/css/style.css' %}">

    <!--carender-->
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% block extrahead %}
    {% endblock %}
    <!--carender end-->

</head>

<body>
    <!--navbar-->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">案件管理APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'akapp:index' %}">INDEX</a>
                    <a class="nav-link" href="{% url 'akapp:anken_list' %}">案件一覧</a>
                    <a class="nav-link" href="{% url 'akapp:anken_create' %}">案件新規作成</a>
                    <a class="nav-link" href="{% url 'akapp:shuho_create' %}">週報新規作成</a>
                </div>
            </div>
            </div>
        </nav>
    </header>
    <!--navbar end-->

    <div><p></p></div>

    {% block content %}
    {% endblock %}
</body>

</html>

akapp/templates/akapp/index.html
{% extends 'akapp/base.html' %}

{% block content %}
<h3>INDEX</h3>
<p><a href="{% url 'akapp:anken_list' %}">案件一覧</a></p>
<p><a href="{% url 'akapp:anken_create' %}">案件新規作成</a></p>
<p><a href="{% url 'akapp:shuho_create' %}">週報新規作成</a></p>
{% endblock %}

akapp/templates/akapp/shuho_create.html
{% extends 'akapp/base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
    <span class="text-secondary">週報新規作成</span><br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="submit" class="btn btn-primary btn-sm" value="保存">
        <input type="reset" class="btn btn-outline-primary btn-sm" value="キャンセル">
        <a href="#" onclick="history.back(); return false;">戻る</a>
    </form>
</div>
{% endblock %}

akapp/templates/akapp/shuho_create_complete.html
{% extends 'akapp/base.html' %}

{% block content %}
<p>投稿が完了しました！</p>
<a href="{% url 'akapp:index' %}">トップへ戻る</a>
{% endblock %}

akapp/templates/akapp/shuho_delete.html
{% extends 'akapp/base.html' %}

{% block content %}
<h3>週報削除</h3>
<form method="post">
    {% csrf_token %}
    <p>{{ shuho.pub_date }}を削除します</p>
    <input type="submit" class="btn btn-danger btn-sm" value="削除">
    <a class="btn btn-outline-primary btn-sm" href="#" onclick="history.back(); return false;">キャンセル</a>
</form>
{% endblock %}

akapp/templates/akapp/shuho_update.html
{% extends 'akapp/base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
    <span class="text-secondary">週報新規作成</span><br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="submit" class="btn btn-primary btn-sm" value="保存">
        <input type="reset" class="btn btn-outline-primary btn-sm" value="キャンセル">
        <a href="{% url 'akapp:anken_detail' shuho.anken.pk %}">戻る</a>
    </form>
</div>
{% endblock %}